# <span style="color:blue">Programming for Data Science - DS-GA 1007</span>
## <span style="color:blue">Assignment 3: Numpy and Pandas - Part I</span>

### Exercise 1 (1.0 point)
Using Numpy, complete the function below. The function should create and return the following 2D array:
```
[[ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]
 [ 5 10 15 20 25 30]]
```
You must find a way to generate the array without typing it explicitly.

In [1]:
import numpy as np

def create_array():
    ### BEGIN SOLUTION
    x=np.linspace(1,30,30,dtype=int)
    y=x.reshape(6,5)
    result=y.transpose()
    ### END SOLUTION
    return result

In [2]:
create_array()

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [3]:
# if your code works properly, the assert below should not raise a message
from numpy.testing import assert_array_equal
assert_array_equal(create_array(), np.array([[ 1, 6, 11, 16, 21, 26],
                                             [ 2, 7, 12, 17, 22, 27],
                                             [ 3, 8, 13, 18, 23, 28],
                                             [ 4, 9, 14, 19, 24, 29],
                                             [ 5, 10, 15, 20, 25, 30]]))

### Exercise 2 (1.0 point)
The function below should return an array containing the second and fourth rows from the input array _original_. The argument (input array) must be a 2D array. If the argument is not a 2D array or does not have the required number of rows, return `None`.

In [4]:
import numpy as np

def new_array_second_and_fourth(original):
    ### BEGIN SOLUTION 
    if str(type(original))== "<class 'numpy.ndarray'>":
        shape=original.shape
    
        if len(shape)!=2 or shape[0]<4:
            return None
        else: 
            return original[[1,3],:]
    else:
        return None
        
    ### END SOLUTION
    return(result)

In [5]:
# if your code works properly, the asserts below should not raise a message
from numpy.testing import assert_array_equal
assert_array_equal(new_array_second_and_fourth([1,2,3]), None)
assert_array_equal(new_array_second_and_fourth(create_array()), 
                   np.array([[ 2, 7, 12, 17, 22, 27],[ 4, 9, 14, 19, 24, 29]]))
assert_array_equal(new_array_second_and_fourth(np.array([1,2,3])), None)
assert_array_equal(new_array_second_and_fourth(np.array([[1,2,3],[4,5,6]])), None)

### Exercise 3 (1.0 point) 
Numpy provides a method called `where`, which allows to find elements in an array that satisfies a conditional statement. Using the method `where`, complete the function below such that it returns an array with the elements from the input array _original_ that are multiple of three. Return `None` if there is no multiple of three. The returned array must be sorted in ascending order. The input must be a Numpy array. If the argument is invalid, return `None`.


In [6]:
import numpy as np

def multi_three(original):
    ### BEGIN SOLUTION
    if str(type(original))== "<class 'numpy.ndarray'>":
        result=original[np.where(original%3==0)]
        result.sort()
        if result.shape==(0,):
            return None
    else:
        return None
    ### END SOLUTION
    return(result)

In [7]:
# if your code works properly, the asserts below should not raise a message
from numpy.testing import assert_array_equal
assert_array_equal(multi_three(create_array()), 
                   np.array([3,6,9,12,15,18,21,24,27,30]))
assert_array_equal(multi_three(np.array([[1,2,15],[1,2,3]])),np.array([3,15]))
assert_array_equal(multi_three(np.array([[3,7,9,2,2,15]])), np.array([3,9,15]))
assert_array_equal(multi_three(np.array([[1,7,1,2,2,2]])), None)
assert_array_equal(multi_three([1,7,1,2,2,2]), None)

### Exercise 4 (1.0 point) 
Numpy provides a method called `logical_and`. Using `logical_and` complete the function below such that it returns an array with the elements from the input array that are in the interval between 3 and 11, inclusive. The returned array must be sorted in descending order. If there is no element in the sought interval the function should return `None`. The argument must be a Numpy array. If the argument is invalid, return `None`.

In [8]:
import numpy as np

def get_interval_descending(original):
    ### BEGIN SOLUTION
    x=original
    result=x[np.logical_and(x>=3,x<=11)]
    result.sort()
    result=result[::-1]
    ### END SOLUTION
    return(result)

In [9]:
# if your code works properly, the asserts below should not raise a message
from numpy.testing import assert_array_equal
assert_array_equal(get_interval_descending(create_array()), np.array([11, 10,  9,  8,  7,  6,  5,  4,  3]))
assert_array_equal(get_interval_descending(np.array([1, 2, 12, 13])), None)
assert_array_equal(get_interval_descending(np.array([[1, 2],[11, 13]])), np.array([11]))

### Exercise 5 (2.0 point) 
The `random_selection` function below should return an 1D array containing the values from each row of the input array _original_ that are closer to the number $1$. 

Hint: Use the numpy method `argsort`.

__PS.__ Refrain from using `for` and `while` loops.

In [10]:
import numpy as np

def random_selection(original):
    ### BEGIN SOLUTION
    B=abs(original-1)
    D=B.argsort()[:,0]
    C=original.shape[0]
    E=list(range(C))
    result=original[E,D]
    ### END SOLUTION
    return(result)

In [12]:
# if your code works properly, the asserts below should not raise a message
from numpy.testing import assert_array_equal
v = np.array([[  0,  -7,  -4],
              [-10,   5,  -1],
              [  6,   3,  -4],
              [  4,   6,   2],
              [ -8,  -4,   6]])
assert_array_equal(random_selection(v), np.array([0, -1,  3,  2, -4]))
assert_array_equal(random_selection(np.array([[-1,0,1],[2.5,0,3]])), np.array([1,0]))

### Exercise 6 (2.0 point) 
Consider the DataFrame `DF` as built in the code below. Using `pandas`, write a function that recieves as input the given DataFrame and return a new DataFrame containing only the rows from coluns $1$ and $3$ whose value in column 'Animal' is _Dino_.

For instance, if this is the input dataframe:
```
     0	1	2	3	4	Animal
-------------------------------
0	8	4	8	7	8	Ptero
1	4	2	7	8	7	Ptero
2	9	9	3	4	4	Dino
3	5	4	3	2	6	Ptero
4	6	8	9	6	7	Dino
5	3	2	9	7	3	Ptero
6	9	2	2	5	7	Ptero
7	1	2	9	2	8	Croco
8	4	1	0	3	7	Croco
9	0	8	2	9	4	
```
the function should return:
````
     1	3	Animal
-------------------
2	9	4	Dino
4	8	6	Dino
```

In [17]:
import pandas as pd
import numpy as np

def select_Dino(df_input):
    ### BEGIN SOLUTION
    x=df_input[df_input["Animal"]=='Dino']
    result=x.iloc[:,[1,3]]
    ### END SOLUTION
    return(result)

In [18]:
# if your code works properly, the asserts below should not raise a message
from numpy.testing import assert_array_equal

M = np.random.randint(low=0,high=10,size=((10,5)))
DF = pd.DataFrame(data=M)
animal_names = ['Croco','Dino','Anacon','Ptero']
animals = np.random.choice(animal_names, 10, p=[0.3, 0.2, 0.2, 0.3])

DF['Animal'] = animals

dinos_ids = np.where(animals == 'Dino')
assert_array_equal(select_Dino(DF)[[1,3]].as_matrix(), M[dinos_ids][:,[1,3]])

### Exercise 7 (2.0 point) 
The `Pandas` module provides a method called `concat` that can be applied to concatenate two Pandas series. Using the method `concat`, complete the function below such that it receives two series S1 and S2 as input and returns a new series containing the most frequent value from S1 and S2 repeated as many times as in S1 and S2. The index of the returned series should match the indices where the frequent values apear in S1 and S2.

For instance, given the series:
```
  S1         S2
------     ------
0    1     0    7
1    6     1    9
2    6     2    2
3    8     3    1
4    2     4    9
5    6     5    0
6    6     6    8
```
the function should return:
```
result
------
1    6
2    6
5    6
6    6
1    9
4    9
```

In [15]:
import pandas as pd
import numpy as n

def concat_frequents(s1,s2):
    ### BEGIN SOLUTION
    mode1=s1.mode()
    mode2=s2.mode()
    result=pd.concat([s1[s1==int(mode1)],s2[s2==int(mode2)]])
    ### END SOLUTION
    return(result)

In [16]:
# if your code works properly, the asserts below should not raise a message
from numpy.testing import assert_array_equal

s1 = pd.Series([1,6,6,8,2,6,6])
s2 = pd.Series([7,9,2,1,9,0,8])

s = concat_frequents(s1,s2)

assert_array_equal(list(s.values),[6, 6, 6, 6, 9, 9])
assert_array_equal(list(s.index),[1, 2, 5, 6, 1, 4])